stages:
  - test
  - build
  
test:
  image: openjdk:11-jdk
  tags:
    - java
  stage: test
  before_script:
    - cd backend
  script:
    - ./mvnw test
  
build:
  image: openjdk:11-jdk
  tags:
    - java
  stage: build
  before_script:
    - cd backend
  script:
    - ./mvnw clean install -DskipTests
