image: openjdk:11-jdk

stages:
  - build-backend
  - deliver
  - deploy

before_script:
  - chmod +x mvnw

build_backend:
  stage: build-backend
  script:
    - ./mvnw test
  only:
    changes:
      - ./backend/
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 2 days