stages:
  - test
  - build
  
test:
  image: openjdk:11-jdk
  tags:
    - maven
  stage: test
  before_script:
    - cd backend
    
  script:
    - mvn test 
  
build:
  image: openjdk:11-jdk
  tags:
    - maven
  stage: build
  before_script:
    - cd backend
  script:
    - mvn clean install -DskipTests
