stages:
  - build
  - package
  - deliver
  - deploy

build:
  image: openjdk:11-jdk
  stage: build
  script:
    - ./mvnw test
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 2 days