stages:
  - test
  - build
  
test:
  image: maven:3-openjdk-11
  tags:
    - java
  stage: test
  before_script:
    - cd backend
    
  script:
    - mvn test 
  
build:
  image: maven:3-openjdk-11
  tags:
    - java
  stage: build
  before_script:
    - cd backend
  script:
    - mvn clean install -DskipTests
