#image: openjdk:11-jdk

#stages:
#  - build-backend
#  - deliver
#  - deploy

before_script:
  - chmod +x mvnw

job1:
  stage: build-backend
  script:
    - ./mvn test
  only:
    changes:
      - ./backend/
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 2 days