stages:
  - build-backend
  - deliver
  - deploy

before_script:
  - chmod +x mvnw

build:
  image: openjdk:11-jdk
  stage: build-backend
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 2 days

build_backend:
  image: openjdk:11-jdk
  stage: build-backend
  script: ./mvnw package
  only:
    changes:
      - ./backend/
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/*
    when: always
    expire_in: 2 days
