stages:
  # - test
  - build
  
# test:
#   image: openjdk:11-jre
#   tags:
#     - maven
#   stage: test
#   before_script:
#     - cd backend
    
#   script:
#     - mvn test 
  
build:
  image: openjdk:11-jre
    - maven
  stage: build
  before_script:
    - cd backend
  script:
    - mvn clean install -DskipTests


stages:
  - build
  - deliver
  
build:
  image: node:12
  stage: build
  before_script:
    - cd frontend
    - npm i
  script:
    - npm run build
  artifacts:
    paths: 
      - frontend/dist/**
    when: always
    expire_in: 2 hours
      
deliver-docker:
  image: gitlab/dind
  stage: deliver
  before_script:
    - cd frontend
  script:
    - docker build -t swtp.pcvolkmer.de/infosys .
    - docker login -u $REPO_USERNAME -p $REPO_PASSWORD swtp.pcvolkmer.de
    - docker push swtp.pcvolkmer.de/infosys