spring:
  application:
    name: gateway
    
  security:
    oauth2:
      client:
        provider:
          swtp:
            issuer-uri: https://swtp.pcvolkmer.de/auth/realms/master
        registration:
          swtp:
            client-id: gateway
            authorized-grant-types: authorization_code, refresh_token
            client-secret: 8bf8ac8f-7621-42dc-b5ef-70d048dc7064
            scope:
              - openid
              - profile

  cloud:
    gateway:
      routes:
        - id: info-portal
          uri: http://localhost:8080
          predicates:
            - Path=/info-portal/ui/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

        - id: info-portal-backend
          uri: http://localhost:8082
          predicates:
            - Path=/info-portal/api/**, /info-portal/doc/**
            # - Path=/**
          filters:
            - TokenRelayWithTokenRefresh=
            - RemoveRequestHeader=Cookie
            
        
server:
  port: 8001
