spring:
  data:
    mongodb:
      uri: mongodb+srv://swtp:swtpinfo@cluster0-vtmhv.mongodb.net/swtp_info?authSource=admin&replicaSet=Cluster0-shard-0&readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=true
server:
  port: 8000